###
GET https://pokedex-zaidoh.herokuapp.com/api/v2/pokemon HTTP/1.1

###
GET http://localhost:3000/api/v2/pokemon/ HTTP/1.1


###
POST  http://localhost:3002/api/v2/pokemon/ HTTP/1.1
Content-Type: application/json

{
    "no": 3,
    "name": "venusaurs "
}

####
PATCH http://localhost:3002/api/v2/pokemon/6351cc7cfaba91c077571cb5 HTTP/1.1
Content-Type: application/json

{
     "name": "bulbasaur2"
}

####
DELETE  http://localhost:3000/api/v2/pokemon/633ce250c332b7ccde3b20a0 HTTP/1.1

####
GET http://localhost:3000/api/v2/seed  HTTP/1.1

####